---
apiVersion: apps/v1
# Change to apps/v1beta2 for K8s < 1.9
kind: StatefulSet
metadata:
  name: fatechain
  namespace: innovation-lab
  labels:
    app: fatechain
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: fatechain
  replicas: 1
  serviceName: fatechain
  template:
    metadata:
      labels:
        app: fatechain
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - fatechain
      volumes:
      - name: fatechain-scripts
        projected:
          sources:
          - configMap:
              name: fatechain-scripts
              items:
              - key: run.sh
                path: run.sh
                mode: 0755
      serviceAccountName: gitlab-ci
      #securityContext:
      #  runAsNonRoot: true
      #  runAsUser: 999
      #  supplementalGroups: [999]
      containers:
      - image: gitlab/gitlab-runner:latest
        imagePullPolicy: IfNotPresent
        name: fatechain
        command:
        - /scripts/run.sh
        envFrom:
        - configMapRef:
            name: fatechain-cm
        - secretRef:
            name: gitlab-ci-token
        env:
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 9100
          name: http-metrics
          protocol: TCP
        volumeMounts:
        - name: fatechain-scripts
          mountPath: "/scripts"
          readOnly: true
      restartPolicy: Always
